wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    session_history: code/_session_history.ipynb
    start_time: 1630298368
    t:
      3:
      - 2
      4: 3.8.5
      5: 0.12.0
      8:
      - 1
      - 5
